### PR TITLE
Update protobuf files

### PR DESCRIPTION
**Pull request by bzz**
Just a quick catch-up with recent changes, on a par with https://github.com/bblfsh/client-python/pull/22

### CODE REVIEW

**Comment by bzz** [comment]
CI fails with
```
[info]   io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service github.com.bblfsh.sdk.protocol.ProtocolService
```

**Comment by abeaumont** [comment]
Thanks @bzz!
It probably should be updated to use `gopkg.in/bblfsh/sdk.v0` instead

**Comment by bzz** [comment]
@abeaumont done in 5f148bf

May be it's also worth deleting https://github.com/bblfsh/client-python/tree/master/github.com/bblfsh/sdk to avoid the confusion?

**Comment by juanjux** [comment]
@bzz they should be renamed, yes (odd that the old files were still in the repository since the generated `_pb2.py` files are ok, I probably copied  them instead of `git mv`) https://github.com/bblfsh/client-python/pull/31

**Comment by juanjux** [comment]
BTW: I can't merge, probably a permissions problem (CC @mcuadros).

**Comment by bzz** [comment]
Thank you for prompt review!

It's very strange.

I have "merge" ⏹, but it would also be nice to get @abeaumont 🏁

**Comment by juanjux** [comment]
Yes, I didn't intend to merge yet, just an observation.

**Comment by abeaumont** [comment]
I can't merge it either, so I guess @bzz can do it for now.
We're currently missing a MAINTAINERS file, so I created a related issue #2.

**Comment by bzz** [comment]
@abeaumont funny enough - I do not have merge button any more 😒 

@mcuadros could you give us a hand here, please?

**Comment by juanjux** [comment]
Yes, it seems "somebody" did a ninja-edit on the permissions :) I'm merging then.

**Pull request merged**
