### PR TITLE
WIP Migrate scala-client to SDK.v2 + libuast.v3

### PR DESCRIPTION
**Pull request by bzz**
TODOs
 - [x] move to SDK.v2
 - [x] `decode()` imp
 - [x] `encode()` impl
 - [x] `load()` impl
 - [ ] `filter()`
 - [ ] `Context` impl (JVM-side factory)
 - [x] move to libuast v3.2.0
 - [ ] iterators
 - [ ] SDK.v1: supported languages/version req + tests
 - [x] C++ improvements: better error handling, extract constants, etc
 - [ ] fix warnings on `-Xcheck:jni`
 - [ ] bump SDK version to latest
 - [ ] expose grpc Deadline though Parse API (similar to #78)

Signed-off-by: Alexander Bezzubov <bzz@apache.org>

### CODE REVIEW

**Comment by bzz** [comment]
Scope updated to include #78 equivalent, but for v2

**Comment by erizocosmico** [comment]
Do we have any estimation for when this will land?

**Comment by bzz** [comment]
> Do we have any estimation for when this will land?

Not yet. I would say it mostly depends on how badly other teams would need it for the next quarters OKRs.

**Comment by bzz** [comment]
Closing in favor of https://github.com/bblfsh/client-scala/issues/83

This code will be re-used, but in smaller chunks, as in #82.

**Pull request closed without merging**
